### ISSUE TITLE
Hapi https connection error when running production build

### ISSUE THREAD

**Issue by eventhough** [luandro/hapi-universal-redux#1]
When testing the production build we don't start an https server so I get a connection refused error.

Would it be better to change https to http on this line: https://github.com/luandro/hapi-universal-redux/blob/master/src/views/Main.js#L167

Otherwise when testing production builds nothing shows.

**Comment by luandro** [comment]
The original [React-Isomorphic-Starterkit](https://github.com/RickWong/react-isomorphic-starterkit) doesn't have this line. I included because I get a HTTPS error when running the project on Heroku.

I suggest you modify it for your needs, since this can vary depending on use case.
