### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by franvarney** [luandro/hapi-universal-redux#41]
When cloning and attempting to run this project currently, there are multiple issues.

The first is `error given was: Error: Unknown handler: proxy` which is the Github route part from server.js#35. I just commented it out to see if I could get this running.

~~Then, I encountered `TypeError: Uncaught error: reply.file is not a function` on server.js#28 which is due to this repo now using a version of hapi.js that requires you to register the Inert plugin. That's easy to fix, so I did that.~~ I think this is due to something else being broken as the original project and other forks do not include Inert (but I haven't figured out how everything is working enough yet.)

Then there's the `Router.run` part in server.js#61. React-router 1.x no longer has the `run` function. So the code needs to be updated or react-router needs to be downgraded to 0.13. 

Are any of these issues going to be fixed? Did you realize these are problems? I can offer to fix some, but I'm new to React/Redux so fixing others is a bit above me at this exact moment.

**Comment by AndrewBestbier** [comment]
+1

**Comment by luandro** [comment]
Almost everything is up to date and working. Still need some final touches on:
- ~~Redux server-side rendering~~
- React server-side rendering is being discarded (on page reload)
- Search isn't working
- Deployed Heroku app isn't working

**Comment by luandro** [comment]
The stater kit is working again. I'll close this multiple issue thread in favor of individual issues.
- React server-side rendering is being discarded (on page reload) #79
- Heroku deployment R10 #80
