### ISSUE TITLE
Invalid checksum on Community avatars.

### ISSUE THREAD

**Issue by luandro** [luandro/hapi-universal-redux#83]
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) 2.3">Community</h3></div></div></div></d
 (server) 2.3">Community</h3><a href="https://gith
```

This happens if the route is changed while avatars are being loaded, or if it's loaded a second time.

**Comment by dlong500** [comment]
Do you have any info on why this is happening or the specific pieces involved?  Just trying to figure out if this is something that would likely occur if I use parts of this starterkit in other projects.

Also, thanks for the work in putting this together.  I was hoping someone was going to put together a hapi-based project with redux that also allowed for server-side rendering, so this came just in time.

**Comment by luandro** [comment]
To be honest, I'm not sure if this is really an issue, since it rarely happens. It probably has to do with the recursive fetching part of the logic. You'll probably use your own. 

I believe it would be safe to use most parts of this. Test it out, and please let me know if you encounter something.
