### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by Download** [luandro/hapi-universal-redux#84]
``` sh
C:\ws\hapi-universal-redux>npm run dev

> hapi-universal-redux@0.5.1 dev C:\ws\hapi-universal-redux
> node ./node_modules/concurrently/src/main.js --kill-others "npm run watch-client" "npm run start"

[0] Active code page: 65001
[1] Active code page: 65001
[1]
[1] > hapi-universal-redux@0.5.1 start C:\ws\hapi-universal-redux
[1] > NODE_PATH="./src" node ./babel-server
[1]
[1] 'NODE_PATH' is not recognized as an internal or external command,
[1] operable program or batch file.
[1]
[1] npm
[1]  ERR! Windows_NT 10.0.10586
...
```

The issue seems to be inherited from [RickWong/react-isomorphic-starterkit](https://github.com/RickWong/react-isomorphic-starterkit/), which has had it from it's incarnation. I created an issue about it that breaks it down and offers 2 solutions:

[Does not work on Windows #88](https://github.com/RickWong/react-isomorphic-starterkit/issues/88)

I hope it can help you make this work on Windows as well.
Good luck and thanks for this project!

**Comment by luandro** [comment]
Hey, thanks for the heads up. Unfortunately I don't have a windows machine to test on. From what I saw from your PR to react-isomorphic-starterkit, the only real change is putting the `harmony` flag instead of `NODE_PATH`.

Would you mind testing and sending PR, I'd be glad to merge.

Cheers!

**Comment by Download** [comment]
Actually, the `harmony` flag is unrelated. It was already in the original code. I just removed the `NODE_PATH="./src"` command. The side effect of this is that it no longer resolves files from the project root, so you will have to change some `require` paths.

I'm sorry but I don't feel like doing the same PR again. This project seems to be a fork of the other one, so I suggest applying the changes yourself if you like this project to work on Windows. It really is a small change. If you remove the env var, your project will break on *nix in the exact same way as it will on Windows. From there you can just fix the require paths.

Good luck!
