### ISSUE TITLE
HMR stateless components not working

### ISSUE THREAD

**Issue by luandro** [luandro/hapi-universal-redux#87]
HMR doesn't work with stateless components. Check out here [85](https://github.com/gaearon/babel-plugin-react-transform/pull/85) and [57](https://github.com/gaearon/babel-plugin-react-transform/issues/57) for the discussion.

**Comment by gaearon** [comment]
You might be interested in https://github.com/reactjs/redux/pull/1455.

**Comment by gaearon** [comment]
React Hot Loader 3 supports functional components without destroying the state.
It supersedes both React Hot Loader and React Transform, and is built on lessons learned from both.
Check it out: https://github.com/gaearon/react-hot-boilerplate/pull/61

**Comment by luandro** [comment]
Thanks @gaearon for the awesome work with React Hot Loader 3.

Moved discussion to #99.
