### ISSUE TITLE
Getting 403 error in the browser whenever I change something on the Client.

### ISSUE THREAD

**Issue by mucholove** [luandro/hapi-universal-redux#88]
Hello!

Server-side hot-updates work perfectly.

However, whenever I change something in one of my Actions, Components, Containers, I am getting 403 error in the browser.

More specifically, it is JSON:

```
  {"statusCode":403,"error":"Forbidden"}
```

I can still see my file on port 8080, but app on 8000 is a no go.

**Comment by luandro** [comment]
I'm getting this error as well, any guesses where it might be coming from?

**Comment by richard-flosi** [comment]
Yup, I ran into the same issue. If you remove the `dist/` directory it will work again, but I don't know what's the real problem or solution is.

**Comment by mucholove** [comment]
Still happening. Sorry for the long intermission. Haven't been coding these last two weeks. Did update my Webpack configs to your current one since my application is already well on it's way. Should I be updating anything else?

**Comment by mucholove** [comment]
@richard-flosi - what do you mean by remove the `/dist` directory?

**Comment by richard-flosi** [comment]
I mean `rm -rf dist/`, but that doesn't really help you with anything b/c the next time you change something it would be broken again. I was just trying to provide a clue to where the issue lies.

**Comment by mucholove** [comment]
I did actually do that, but it still didn't work. Which is why I was curious.

**Comment by luandro** [comment]
As Dan pointed out in #87, it's now recommended to remove React-Transform. I plan on working on it #94, any help is welcome. That should do the trick.

**Comment by mucholove** [comment]
Never contributed to a repository like this before! Let's see if I can try this out before anything else blows up. A pointer would be nice..but I will be deep-diving regardless!

**Comment by luandro** [comment]
[These](https://github.com/reactjs/redux/pull/1455/files) are basically the changes you'll have to do. Just fork my repo, make the changes and submit the pull request if you can get it to work :+1:
