### ISSUE TITLE
sass setup

### ISSUE THREAD

**Issue by jamesone** [luandro/hapi-universal-redux#97]
I'm not sure Radium is the best option for larger scaled web-apps. I think it'd be best for a sass setup to be implemented?

Thoughts?

**Comment by luandro** [comment]
Once code-splitting is implemented, I personally don't see why Radium doesn't scale.

**Comment by jamesone** [comment]
@luandro  - Yeah true, I think sass is a better solution overall as it's widely used for front-end stuff. When I get time I will try and post a sass solution.
